### ISSUE TITLE
not getting token on a Essenza Plus

### ISSUE THREAD

**Issue by plckr** [petergullberg/brewbutton#1]
Hello,

thanks for your work. It's really awesome, really!

I bought a new nespresso with the connectivity funcion.
It seems that it's different from the Expert model which can take expresso from remote, atleast I can't do that via their app, maybe it's possible but hidden idk

The thing is I can't extract the token, I have messing around in the app during the HCI snoop is active, then opened it in wireshark but can't find a packet which is 16 length and has the UUID 0x0014 

any idea?

firmware machine: 6.0
connectivity firmware: 1.1.0

**Comment by petergullberg** [comment]
I do only have access to my own machine, I enclose a dump and "my" key for your reference.

Here is how the AUTH key is written to my nespresso:
localhost ()	d0:09:e2:58:54:b8 ()	ATT	20	Sent Write Request, Handle: **0x0014** (Unknown)
DATA:  02 40 00 0f 00 0b 00 04 00 12 14 00 **87 96 08 e2 7c b1 f9 6e**                                       |..
![nespresso](https://user-images.githubusercontent.com/6551101/73769849-b1566480-477b-11ea-92b9-e7b2e49f953e.png)

**Comment by plckr** [comment]
The protocol probably is different because I can't find any 0x0014
I see that the length is 20. Searching for all 20's and shows me one packet with a value. Seems identical

![wireshark](https://user-images.githubusercontent.com/11768109/73793123-a3b1d680-479d-11ea-834e-682df2d06356.png)

what do you think?

**Comment by plckr** [comment]
can you tell me which version is your **machine** and **connectivity** firmware?

**Comment by tikismoke** [comment]
For me it works with a nespresso prodigio&milk

**Comment by tikismoke** [comment]
@ricreis394 
Seems you found your Auth code in the capture picture 8e4bdce462ea9078

Doesn't this work.

**Comment by petergullberg** [comment]
@ricreis394  sorry, didn't see your response. Yes, it looks like that this is the auth-code. Maybe on your model, the Characteristics (06aa3a41-f22a-11e3-9daa-0002a5d5c51b) is located on 0x0012. Try follow the guide using this value.

My machine is a nespresso expert, version 6.0, connectivity firmware 1.27 (iPhone)
