### ISSUE TITLE
My first decode participation

### ISSUE THREAD

**Issue by tikismoke** [petergullberg/brewbutton#2]
Hi use a nespresso prodigio&milk and the apps is the same so i' going to put my decode value here.

I let you merge this in the readme to help others.

Also my machine need descaling ("detartrage" in french) so i have different value i hope to find what byte (or value changed) when i'll done it.
For example the  for value i get:
```
06aa3a12-f22a-11e3-9daa-0002a5d5c51b
44 09 80 0C C0 00 00
44 09 80 2D C0 00 00
44 09 07 2D C0 00 00
44 09 07 1D 0C C0 00 00 00
```

**06aa3a15-f22a-11e3-9daa-0002a5d5c51b** is the **caps remaining in stock** in hex format (if you have add them in the apps)
Value got from 00:00 to 03:E8 (from 0 caps to 1000).
But it can also contain from 03:E9 to FF:FF and in apps it appears a '+' instead of the caps value and ask you to follow caps purchase in apps (as if it was deactivate)
The apps can notify you when value is low.

```
06aa3a44-f22a-11e3-9daa-0002a5d5c51b
07 08 04 00
07 08 03 00
```
byte 3.0 (04 or 03) is the "water hardness" ("dureté de l'eau" in french) set in the apps (from 0 to 4)
Try to send 5 or more and the value change to 4 automatically (seems that the cofee machine maintain it too a correct value)

**Comment by tikismoke** [comment]
This machine have only 3 buttons for 3 differents cofee volume.
So command is lungo/expresso/ristretto
Write to:
```
Service UUID: 06aa1920f22a11e39daa0002a5d5c51b
UUID: 06aa3a42-f22a-11e3-9daa-0002a5d5c51b
Value: 03050704000000000002 for lungo
Value: 03050704000000000001 for expresso
Value: 03050704000000000000 for ristretto
```

**Comment by petergullberg** [comment]
Great! I have integrated your first comments. After I descaled my machine, The bytes B6&B7 was not returned. I assume they have som internal (larger counter) inside the machine. As far as I can tell, these bytes are an estimation of time to descaling is required. It appears that the machine decrease with two different values, one is the amount of time the machine is one, and the other is a decrase value for each time it brews coffee.

**Comment by tikismoke** [comment]
> Great! I have integrated your first comments. After I descaled my machine, The bytes B6&B7 was not returned. I assume they have som internal (larger counter) inside the machine. As far as I can tell, these bytes are an estimation of time to descaling is required. It appears that the machine decrease with two different values, one is the amount of time the machine is one, and the other is a decrase value for each time it brews coffee.

I'm going to descaled it and tell you in few minutes what changed.

Also when water is empty i got this:
06aa3a12-f22a-11e3-9daa-0002a5d5c51b:
45 02 1C 2C C0 00 00 00

**Comment by tikismoke** [comment]
Once descaled i got: 
 06aa3a12-f22a-11e3-9daa-0002a5d5c51b:
41 02 1C 2C C0 00 0F A0

**Comment by tikismoke** [comment]
New things found in fact to be found...
I was trying to make coffee but it was not working from python... After a while I launch the official apps and:
I'll post the image later...

In the apps an error occured in my case if I do not have open the tray since last coffee make (error 1032 in Nespresso apps). Indeed it means no new caps have been engaged and none is in the tray.

So I think this information is somewhere in the machine. Just need to find where.

**Comment by tikismoke** [comment]
This is a complete phase:
Ask for a coffee
NEW caps in place, machine was sleeping and cold
```
40091220c0000c0a
0100 0000 0000 1001 0001 0010 0010 0000 1100 00000000 00000000 11000000101
```
Machine ready
```
40011224c0000c0a
0100 0000 0000 0001 0001 0010 0010 0100 1100 00000000 00000000 11000000101
```
Coffee flows
```
40841224c0000c09
0100 0000 1000 0100 0001 0010 0010 0100 1100 00000000 00000000 1100 0000 1001
40841224c0000c08
0100 0000 1000 0100 0001 0010 0010 0100 1100 00000000 00000000 1100 0000 1000
40841224c0000c07
0100 0000 1000 0100 0001 0010 0010 0100 1100 00000000 00000000 1100 0000 0111
40841224c0000c00
0100 0000 1000 0100 0001 0010 0010 0100 1100 00000000 00000000 1100 0000 0000
40021224c0000bff
0100 0000 0000 0010 0001 0010 0010 0100 1100 0000 0000 0000000 0101 1111 11111
```
Finished
Caps removed
```
40021204c0000bff
0100 0000 0000 0010 0001 0010 0000 0100 1100 00000000 00000000 1011 1111 1111
```
...
a little time later
```
40091204c0000bff'
0100 0000 0000 1001 0001 0010 0000 0100 1100 00000000 00000000 1011 1111 1111
```
Another day caps trash full machine sleeping new caps engadge:
```
404911a4c0000bde
0100 0000 0100 1001 0001 0001 1010 0100 1100 00000000 00000000 1011 1101 1110
```
Confirms same for trap open or full on byte 1 bit 7 as describred in readme.

So i'm pretty sure the caps presence is in the byte 3 that's the only change (xx1x xxx when caps presence is detect and xx0x xxxx when caps is in the machine trash)
In this case no more command to make coffee flow again works. (my previous comment about error 1032)
To see if all machine do the same.

**Comment by tikismoke** [comment]
I update my script to have more debug:

machine was sleeping and water cold:
```
400911a4c0000bde
0100 0000 0000 1001 0001 0001 1010 0100 1100 000000000000000010111101111
```
Machine was no more sleeping but preparing, led blinking to make water hot or something else, like when you press the button, in this case the machine is awake but not byte B1.2
```
400111a8c0000bde
0100 0000 0000 0001 0001 0001 1010 1000 1100 000000000000000010111101111
```
then coffee flow as usual no more cold water in B1.0 but awake B1.1change to 1:
```
400211a8c0000bde
0100 0000 0000 0010 0001 0001 1010 1000 1100 000000000000000010111101111
```
So byte 3 low bit change from 0100 to 1000 thinking it's an indicating for preparing or something else like this.

**Comment by tikismoke** [comment]
About descaled bit I'm a little confused.

Currently the apps tell me it's necessary but the bit didn't pass to 1.

Maybe only the counter decrease to 0 I'll to check that.

I have to investigate more. And in this case what is the role of the identified descaled_need bit? As it pass to 0 when descaled done...

**Comment by tikismoke** [comment]
current state value is b'440926acc0000193'

**Comment by tikismoke** [comment]
> About descaled bit I'm a little confused.
> 
> Currently the apps tell me it's necessary but the bit didn't pass to 1.
> 
> Maybe only the counter decrease to 0 I'll to check that.
> 
> I have to investigate more. And in this case what is the role of the identified descaled_need bit? As it pass to 0 when descaled done...

Craps :( descaled_needed is on byte0.2 not 0.3 as i've notice in my patch

I've update[ my patch](https://github.com/petergullberg/brewbutton/pull/3/commits/fa02960d5a7302ededc8fca08bb0d313c872bbb8)

**Comment by tikismoke** [comment]
While in descaling mode i've got : 418326acc0000fa0
And back to normal mode: 410226acc0000fa0

Nothing here that tell us descaling is running.

**Comment by petergullberg** [comment]
I have processed all your comments, there are a few resolutions to be made. I will need to descale my nespresso in the coming week(s), so I will update the documentation afterwards

**Comment by tikismoke** [comment]
@petergullberg 

could you tell me with is the second status to monitor:

```
[d2:12:f1:7b:cd:6d]    Characteristic [00002a00-0000-1000-8000-00805f9b34fb]
Read UUID 00002a00-0000-1000-8000-00805f9b34fb: b'50726f646967696f264d696c6b5f4432313246'
bytearray(b'Prodigio&Milk_D212F')
[d2:12:f1:7b:cd:6d]    Characteristic [00002a01-0000-1000-8000-00805f9b34fb]
Read UUID 00002a01-0000-1000-8000-00805f9b34fb: b'0000'
bytearray(b'\x00\x00')
[d2:12:f1:7b:cd:6d]    Characteristic [00002a04-0000-1000-8000-00805f9b34fb]
Read UUID 00002a04-0000-1000-8000-00805f9b34fb: b'06000c0000009001'
bytearray(b'\x06\x00\x0c\x00\x00\x00\x90\x01')
[d2:12:f1:7b:cd:6d]    Characteristic [00002a05-0000-1000-8000-00805f9b34fb]
Read error for UUID [00002a05-0000-1000-8000-00805f9b34fb]
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a11-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a11-f22a-11e3-9daa-0002a5d5c51b: b'0064ffff'
bytearray(b'\x00d\xff\xff')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a21-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a21-f22a-11e3-9daa-0002a5d5c51b: b'006c006d007d0076d212f17bcd6d'
bytearray(b'\x00l\x00m\x00}\x00v\xd2\x12\xf1{\xcdm')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a31-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a31-f22a-11e3-9daa-0002a5d5c51b: b'31363036384337357031323038353832303436'
bytearray(b'16068C75p1208582046')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a41-f22a-11e3-9daa-0002a5d5c51b]
Read error for UUID [06aa3a41-f22a-11e3-9daa-0002a5d5c51b]
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a51-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a51-f22a-11e3-9daa-0002a5d5c51b: b'02'
bytearray(b'\x02')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a61-f22a-11e3-9daa-0002a5d5c51b]
Read error for UUID [06aa3a61-f22a-11e3-9daa-0002a5d5c51b]
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a12-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a12-f22a-11e3-9daa-0002a5d5c51b: b'40091668c00009df'
bytearray(b'@\t\x16h\xc0\x00\t\xdf')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a22-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a22-f22a-11e3-9daa-0002a5d5c51b: b'02'
bytearray(b'\x02')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a32-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a32-f22a-11e3-9daa-0002a5d5c51b: b'000000000000'
bytearray(b'\x00\x00\x00\x00\x00\x00')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a42-f22a-11e3-9daa-0002a5d5c51b]
Read error for UUID [06aa3a42-f22a-11e3-9daa-0002a5d5c51b]
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a52-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a52-f22a-11e3-9daa-0002a5d5c51b: b'00000000000000000000000000000000000000'
bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a13-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a13-f22a-11e3-9daa-0002a5d5c51b: b'00'
bytearray(b'\x00')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a23-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a23-f22a-11e3-9daa-0002a5d5c51b: b'00000000000000000000000000000000000000'
bytearray(b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a14-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a14-f22a-11e3-9daa-0002a5d5c51b: b'0000'
bytearray(b'\x00\x00')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a24-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a24-f22a-11e3-9daa-0002a5d5c51b: b'00000000'
bytearray(b'\x00\x00\x00\x00')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a34-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a34-f22a-11e3-9daa-0002a5d5c51b: b'00'
bytearray(b'\x00')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a44-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a44-f22a-11e3-9daa-0002a5d5c51b: b'07080400'
bytearray(b'\x07\x08\x04\x00')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a15-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a15-f22a-11e3-9daa-0002a5d5c51b: b'00b3'
bytearray(b'\x00\xb3')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a25-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a25-f22a-11e3-9daa-0002a5d5c51b: b'0032'
bytearray(b'\x002')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a35-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a35-f22a-11e3-9daa-0002a5d5c51b: b'0000d244'
bytearray(b'\x00\x00\xd2D')
[d2:12:f1:7b:cd:6d]    Characteristic [06aa3a45-f22a-11e3-9daa-0002a5d5c51b]
Read UUID 06aa3a45-f22a-11e3-9daa-0002a5d5c51b: b'01'

```
