### ISSUE TITLE
descale needed

### ISSUE THREAD

**Issue by tikismoke** [petergullberg/brewbutton#4]
Hi peter,

The descaled value passed to True on yesterday, finally YES.
BAD:
-The red light didn't light up physically in the machine :(
-Count down as not reach 0 (it start to say descale need at ~600 (still not know what sort of unit it is..)
GOOD
-The Nespresso apps also say that descaled is need.

I'm going to look if something else changed when red light will switch to ON (count down to 0?)

**Comment by petergullberg** [comment]
I'm also unclear on the units, I did monitored it quite intensively, and I think it's a mixture of number of brews, combined with on-time of the machine.

**Comment by tikismoke** [comment]
Count down to zero and as expected red light is on on the machine ;)
This validate our thought.

So counter is at less use to power on red led. But descaled needed information is shown before on apps and in the value we get.
