### ISSUE TITLE
Dont have acess to a Android Phone, is there another way?

### ISSUE THREAD

**Issue by delgadillo-oraculo** [petergullberg/brewbutton#7]
Is there aniway to find the  Nespresso AUTH-KEY using windows or a jailbroken iphone?
i've already tried a WSA Android on windows 11 , currently it doesnt support BLE

**Comment by petergullberg** [comment]
One way would be to use a virtual BLE peripheral cloner/simulator and two phones (one to simulate and one to run your nespresso app). Lightblue is such an app, but it seems that iOS won't allow you to simulate the name (it remains the iOS name). I have thought about it, but not investigated it further.
